version: "3.4"
services:
  drexel-tms-parser:
    image: drexel-tms-parser-image
    container_name: drexel-tms-parser-webserver
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
