version: "3.4"
services:
  drexel-tms-webserver:
    image: drexel-tms-webserver-image
    container_name: drexel-tms-webserver
    env_file:
     - ./src/db/.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 5000
        SERVLET: webapp.py
    ports:
      - "5000:5000"
    volumes:
      - .:/home/drexel-tms-parser
    networks:
      - drexel-tms-network

  drexel-tms-crawler:
    image: drexel-tms-crawler-image
    container_name: drexel-tms-crawler
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 4000
        SERVLET: crawler_runner.py
    volumes:
      - .:/home/drexel-tms-parser
    networks:
      - drexel-tms-network
    links:
      - drexel-tms-ingest
    depends_on:
      - drexel-tms-ingest

  drexel-tms-ingest:
    image: drexel-tms-ingest-image
    container_name: drexel-tms-ingest
    env_file:
    - ./src/db/.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 5001
        SERVLET: data_ingestor.py
    ports:
      - "5001:5001"
    volumes:
      - .:/home/drexel-tms-parser
    networks:
      - drexel-tms-network

  webserver:
    image: nginx:alpine
    container_name: drexel-tms-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - drexel-tms-network

networks:
  drexel-tms-network:
    driver: bridge
