version: "3.4"
services:
  drexel-tms-parser:
    image: drexel-tms-parser-image
    container_name: drexel-tms-parser-webserver
    env_file:
     - ./src/db/.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 5000
        SERVLET: app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/home/drexel-tms-parser
    networks:
    - d-tms-network

  drexel-tms-ingest:
    image: drexel-tms-ingest
    container_name: drexel-tms-ingest
    env_file:
    - ./src/db/.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 5001
        SERVLET: data_ingestor.py
    ports:
      - "5001:5001"
    volumes:
    - .:/home/drexel-tms-parser
    networks:
      - d-tms-network

  webserver:
    image: nginx:alpine
    container_name: drexel-tms-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - d-tms-network

networks: 
  d-tms-network:
    driver: bridge