version: "3.4"
services:
  drexel-tms-parser:
    image: drexel-tms-parser-image
    container_name: drexel-tms-parser-webserver
    env_file:
     - ./src/db/.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/home/drexel-tms-parser
