version: "3.4"
services:
  drexel-tms-parser:
    image: drexel-tms-parser-image
    container_name: drexel-tms-parser-webserver
    env_file:
     - ./src/db/.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 5000
        SERVLET: app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/home/drexel-tms-parser
  drexel-tms-injest:
    image: drexel-tms-injest
    container_name: drexel-tms-injest
    env_file:
    - ./src/db/.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PORT: 5001
        SERVLET: data_ingestor.py
    ports:
      - "5001:5001"
    volumes:
    - .:/home/drexel-tms-parser
