version: 2
jobs:
  build_python:
    working_directory:  ~/drexel-tms-parser
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
        command: |
          bash install.sh
          source ./venv/bin/activate
          pip install -r requirements.txt
  test_python:
    working_directory:  ~/drexel-tms-parser
    docker:
      - image: circleci/python:3.7.2
    steps:
      - run:
        command: |
          source ./venv/bin/activate
          python -m unittest discover -s test/python

workflows:
  version: 2
  build_and_test_python:
    jobs:
      - build_python
      - test_python